{{- if and (not .Values.rbac.only) .Values.agentInjector.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: telepresence-intercept-env
  namespace:  {{ include "traffic-manager.namespace" . }}
data:
  excluded: |
  {{- range .Values.intercept.environment.excluded }}
    {{ . }}
  {{- end }}
{{- end }}
