name: "Build and Unit test"
on:
  pull_request_target:
env:
  HOMEBREW_NO_INSTALL_FROM_API:
jobs:
  unit:
    strategy:
      fail-fast: false
      matrix:
        runners:
          - ubuntu-latest
          - ubuntu-arm64
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.runners }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: "${{ github.event.pull_request.head.sha }}"
      - name: install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Lint
        run: make lint
      - name: Build
        run: make build
      - name: Run tests
        uses: nick-fields/retry/@v3
        with:
          max_attempts: 3
          timeout_minutes: 12
          command: make check-unit
